import { AnimatePresence, motion } from 'framer-motion'
import { useEffect, useState } from 'react'
import { categories, hairStyles } from '../data/styles'

export default function StyleGallery(){const[category,setCategory]=useState('ALL'),[selected,setSelected]=useState(null);const items=category==='ALL'?hairStyles:hairStyles.filter(s=>s.category===category)
useEffect(()=>{const fn=e=>e.key==='Escape'&&setSelected(null);addEventListener('keydown',fn);document.body.classList.toggle('modal-open',!!selected);return()=>{removeEventListener('keydown',fn);document.body.classList.remove('modal-open')}},[selected])
return <section className="styles section-theme" id="style" data-bg="#f7f5f0"><div className="section-head"><p className="eyebrow">02 — EDITORIAL</p><h2>HAIR STYLE</h2><p>形、質感、光。あなたらしさを構成する細部まで。</p></div><div className="filters" role="group" aria-label="ヘアスタイルカテゴリー">{categories.map(c=><button className={category===c?'active':''} key={c} onClick={()=>setCategory(c)}>{c}</button>)}</div>
<motion.div layout className="style-grid"> <AnimatePresence mode="popLayout">{items.map((s,i)=><motion.button layout key={s.id} className={`style-tile tile-${(i%6)+1}`} initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} exit={{opacity:0,y:25}} transition={{duration:.45}} onClick={()=>setSelected(s)} data-cursor="OPEN"><img src={s.image} alt={`${s.name}のヘアスタイル`} width="900" height="1125" loading="lazy" decoding="async"/><span className="style-overlay"><small>{s.category}</small><strong>{s.name}</strong><em>VIEW STYLE ↗</em></span></motion.button>)}</AnimatePresence></motion.div>
<AnimatePresence>{selected&&<motion.div className="modal-backdrop" initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} onMouseDown={()=>setSelected(null)}><motion.div className="style-modal" role="dialog" aria-modal="true" aria-labelledby="style-modal-title" initial={{opacity:0,scale:.96,y:30}} animate={{opacity:1,scale:1,y:0}} exit={{opacity:0,scale:.96}} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setSelected(null)} aria-label="モーダルを閉じる">×</button><img src={selected.image} alt={`${selected.name}の拡大写真`}/><div><p className="eyebrow">{selected.category}</p><h3 id="style-modal-title">{selected.name}</h3><dl><div><dt>LENGTH</dt><dd>{selected.length}</dd></div><div><dt>RECOMMEND</dt><dd>{selected.menu}</dd></div><div><dt>STYLIST</dt><dd>{selected.stylist}</dd></div></dl></div></motion.div></motion.div>}</AnimatePresence></section>}
